# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  blueshoon.com:
    site_hosts:
      - canonical: blueshoon.test
        redirects:
          - www.blueshoon.test
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@blueshoon.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    repo: git@github.com:blueshoon/blueshoon.git
    wpe_instance: blueshoon
    wpe_ssh_server: blueshoon.ssh.wpengine.net
    wpe_ssh_user: blueshoon
