---
- name: get repo
  delegate_to: 127.0.0.1
  become: no
  git:
    repo: "{{ item.value.repo }}"
    dest: ../site/web/repo
  with_dict: "{{ wordpress_sites }}"

- name: export wordpress db
  become: no
  command: "ssh {{ item.value.wpe_ssh_user }}@{{ item.value.wpe_ssh_server }} /usr/local/bin/wp db export sites/{{ item.value.wpe_instance }}/wp-content/export.sql --add-drop-table"
  delegate_to: 127.0.0.1
  with_dict: "{{ wordpress_sites }}"
  register: result

- name: get uploads
  delegate_to: 127.0.0.1
  become: no
  command: "rsync -avz --exclude 'mu-plugins' --exclude 'ai1wm-backups' --exclude 'themes' {{ item.value.wpe_ssh_user }}@{{ item.value.wpe_ssh_server }}:sites/{{ item.value.wpe_instance }}/wp-content/ ../site/web/repo/wp-content/"
  with_dict: "{{ wordpress_sites }}"

- name: Import Instance DB
  become: no
  command: wp db import mysql.sql
  args:
    chdir: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/web/repo/wp-content/"
  with_dict: "{{ wordpress_sites }}"

- name: Replace domain
  become: no
  command: "wp search-replace 'http[s]?://{{ item.key }}' 'http://{{ item.value.site_hosts[0].canonical }}' --regex"
  args:
    chdir: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/web/repo/wp-content/"
  with_dict: "{{ wordpress_sites }}"
