---
- name: install npm package
  delegate_to: 127.0.0.1
  become: no
  command: npm i
  args:
    chdir: "../site/web/{{ wpe_instance }}/wp-content/themes/sassapress"
  with_dict: "{{ wordpress_sites }}"
