---
- name: install node packages
  nodejs_package_json_path: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/web/{{ item.value.wpe_instance }}"
  with_dict: "{{ wordpress_sites }}"
  become: no
